<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <title>Document</title>
</head>

<body>
    <div class="wrapper">
        <?php if ($error != null) { ?>
            <small><?= $error ?></small>
        <?php } ?>
        <div class="container">
            <div class="login">
                <h1>Welcome</h1>
                <form class="form" action="login.php" method="post">
                    <input type="text" name="email" placeholder="email/pseudo" required>
                    <input type="password" name="password" placeholder="Password" required>
                    <button type="submit" id="login-button">Connexion</button>
                </form>
            </div>
            <div class="register">
                <h1>Pas encore de compte?</h1>
                <form class="form" action="register.php" method="post">
                    <input type="text" name="pseudo" placeholder="Username" required>
                    <input type="text" name="firstname" placeholder="Firstname" required>
                    <input type="text" name="lastname" placeholder="Lastname" required>
                    <input type="mail" name="email" placeholder="Email" required>
                    <input type="text" name="promo" placeholder="Promo" required>
                    <input type="text" name="campus" placeholder="Campus" required>
                    <input type="password" name="password" placeholder="Password" required>
                    <button type="submit" id="login-button">S'enregistrer</button>
                </form>
            </div>
        </div>

        <ul class="bg-bubbles">
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
        </ul>
    </div>
</body>

</html>